name: Build & Deploy Frontend

on:
  repository_dispatch:
    types:
      - frontend
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: front-despacho
  EKS_CLUSTER_NAME: nota3-Cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push de la imagen Docker a ECR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          context: .
          file: ./Dockerfile
          build-args: |
            VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Actualizar kubeconfig para EKS
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy a EKS
        run: kubectl apply -f k8s/

      - name: Reiniciar Deployment para tomar nueva imagen
        run: kubectl rollout restart deployment/frontend

      - name: Esperar rollout
        run: kubectl rollout status deployment/frontend --timeout=300s
